name = "Friendships"
uuid = "a6110d29-88b6-47c1-b693-fa0b03c6b846"
version = "1.0.0-DEV"
authors = ["Sarah Boukhari <saraah.bhr@icloud.com> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
LinearAlgebra = "1.6"
Random = "1.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
